spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/checklist_nasr
    username: postgres
    password: postgres

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8080

  tomcat:
    threads:
      max: 20
    accept-count: 20